export default {
  /* USER */
  GET_CURRENT_USER: 'GET_CURRENT_USER',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_ERROR: 'GET_CURRENT_USER_ERROR',

  INCREMENT_USER_IBISOKOZOADDED_REQUEST: 'INCREMENT_USER_IBISOKOZOADDED_REQUEST',
  INCREMENT_USER_IBISOKOZOADDED_SUCCESS: 'INCREMENT_USER_IBISOKOZOADDED_SUCCESS',
  INCREMENT_USER_IBISOKOZOADDED_ERROR: 'INCREMENT_USER_IBISOKOZOADDED_ERROR',

  ADD_PLAYEDSOKOZO_ID_REQUEST: 'ADD_PLAYEDSOKOZO_ID_REQUEST',
  ADD_PLAYEDSOKOZO_ID_SUCCESS: 'ADD_PLAYEDSOKOZO_ID_SUCCESS',
  ADD_PLAYEDSOKOZO_ID_ERROR: 'ADD_PLAYEDSOKOZO_ID_ERROR',

  INCREMENT_USER_SCORE_REQUEST: 'INCREMENT_USER_SCORE_REQUEST',
  INCREMENT_USER_SCORE_SUCCESS: 'INCREMENT_USER_SCORE_SUCCESS',
  INCREMENT_USER_SCORE_ERROR: 'INCREMENT_USER_SCORE_ERROR',

  /* USERS */
  FETCH_USERS: 'FETCH_USERS',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_ERROR: 'FETCH_USERS_ERROR',

  /* Ibisokozo */
  FETCH_IBISOKOZO: 'FETCH_IBISOKOZO',
  FETCH_IBISOKOZO_SUCCESS: 'FETCH_IBISOKOZO_SUCCESS',
  FETCH_IBISOKOZO_ERROR: 'FETCH_IBISOKOZO_ERROR',

  /* Igisokozo */
  GET_IGISOKOZO: 'GET_IGISOKOZO',
  GET_IGISOKOZO_SUCCESS: 'GET_IGISOKOZO_SUCCESS',
  GET_IGISOKOZO_ERROR: 'GET_IGISOKOZO_ERROR',

  ADD_IGISOKOZO_REQUEST: 'ADD_IGISOKOZO_REQUEST',
  ADD_IGISOKOZO_SUCCESS: 'ADD_IGISOKOZO_SUCCESS',
  ADD_IGISOKOZO_ERROR: 'ADD_IGISOKOZO_ERROR',

  DELETE_IGISOKOZO_REQUEST: 'DELETE_IGISOKOZO_REQUEST',
  DELETE_IGISOKOZO_SUCCESS: 'DELETE_IGISOKOZO_SUCCESS',
  DELETE_IGISOKOZO_ERROR: 'DELETE_IGISOKOZO_ERROR',

  UPDATE_IGISOKOZO_REQUEST: 'UPDATE_IGISOKOZO_REQUEST',
  UPDATE_IGISOKOZO_SUCCESS: 'UPDATE_IGISOKOZO_SUCCESS',
  UPDATE_IGISOKOZO_ERROR: 'UPDATE_IGISOKOZO_ERROR',
};
