/* USER */
const GET_CURRENT_USER = 'GET_CURRENT_USER';
const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
const GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR';

const INCREMENT_USER_IBISOKOZOADDED_REQUEST = 'INCREMENT_USER_IBISOKOZOADDED_REQUEST';
const INCREMENT_USER_IBISOKOZOADDED_SUCCESS = 'INCREMENT_USER_IBISOKOZOADDED_SUCCESS';
const INCREMENT_USER_IBISOKOZOADDED_ERROR = 'INCREMENT_USER_IBISOKOZOADDED_ERROR';

const ADD_PLAYEDSOKOZO_ID_REQUEST = 'ADD_PLAYEDSOKOZO_ID_REQUEST';
const ADD_PLAYEDSOKOZO_ID_SUCCESS = 'ADD_PLAYEDSOKOZO_ID_SUCCESS';
const ADD_PLAYEDSOKOZO_ID_ERROR = 'ADD_PLAYEDSOKOZO_ID_ERROR';

const INCREMENT_USER_SCORE_REQUEST = 'INCREMENT_USER_SCORE_REQUEST';
const INCREMENT_USER_SCORE_SUCCESS = 'INCREMENT_USER_SCORE_SUCCESS';
const INCREMENT_USER_SCORE_ERROR = 'INCREMENT_USER_SCORE_ERROR';

/* USERS */
const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

/* Ibisokozo */
const FETCH_IBISOKOZO = 'FETCH_IBISOKOZO';
const FETCH_IBISOKOZO_SUCCESS = 'FETCH_IBISOKOZO_SUCCESS';
const FETCH_IBISOKOZO_ERROR = 'FETCH_IBISOKOZO_ERROR';

/* Igisokozo */
const GET_IGISOKOZO = 'GET_IGISOKOZO';
const GET_IGISOKOZO_SUCCESS = 'GET_IGISOKOZO_SUCCESS';
const GET_IGISOKOZO_ERROR = 'GET_IGISOKOZO_ERROR';

const GET_IGISOKOZO_BYID = 'GET_IGISOKOZO_BYID';
const GET_IGISOKOZO_BYID_SUCCESS = 'GET_IGISOKOZO_BYID_SUCCESS';
const GET_IGISOKOZO_BYID_ERROR = 'GET_IGISOKOZO_BYID_ERROR';

const ADD_IGISOKOZO_REQUEST = 'ADD_IGISOKOZO_REQUEST';
const ADD_IGISOKOZO_SUCCESS = 'ADD_IGISOKOZO_SUCCESS';
const ADD_IGISOKOZO_ERROR = 'ADD_IGISOKOZO_ERROR';

const DELETE_IGISOKOZO_REQUEST = 'DELETE_IGISOKOZO_REQUEST';
const DELETE_IGISOKOZO_SUCCESS = 'DELETE_IGISOKOZO_SUCCESS';
const DELETE_IGISOKOZO_ERROR = 'DELETE_IGISOKOZO_ERROR';

const UPDATE_IGISOKOZO_REQUEST = 'UPDATE_IGISOKOZO_REQUEST';
const UPDATE_IGISOKOZO_SUCCESS = 'UPDATE_IGISOKOZO_SUCCESS';
const UPDATE_IGISOKOZO_ERROR = 'UPDATE_IGISOKOZO_ERROR';

export {
  GET_CURRENT_USER,
  GET_CURRENT_USER_SUCCESS,
  GET_CURRENT_USER_ERROR,
  INCREMENT_USER_IBISOKOZOADDED_REQUEST,
  INCREMENT_USER_IBISOKOZOADDED_SUCCESS,
  INCREMENT_USER_IBISOKOZOADDED_ERROR,
  ADD_PLAYEDSOKOZO_ID_REQUEST,
  ADD_PLAYEDSOKOZO_ID_SUCCESS,
  ADD_PLAYEDSOKOZO_ID_ERROR,
  INCREMENT_USER_SCORE_REQUEST,
  INCREMENT_USER_SCORE_SUCCESS,
  INCREMENT_USER_SCORE_ERROR,
  FETCH_USERS_REQUEST,
  FETCH_USERS_SUCCESS,
  FETCH_USERS_ERROR,
  FETCH_IBISOKOZO,
  FETCH_IBISOKOZO_SUCCESS,
  FETCH_IBISOKOZO_ERROR,
  GET_IGISOKOZO,
  GET_IGISOKOZO_SUCCESS,
  GET_IGISOKOZO_ERROR,
  GET_IGISOKOZO_BYID,
  GET_IGISOKOZO_BYID_SUCCESS,
  GET_IGISOKOZO_BYID_ERROR,
  ADD_IGISOKOZO_REQUEST,
  ADD_IGISOKOZO_SUCCESS,
  ADD_IGISOKOZO_ERROR,
  DELETE_IGISOKOZO_REQUEST,
  DELETE_IGISOKOZO_SUCCESS,
  DELETE_IGISOKOZO_ERROR,
  UPDATE_IGISOKOZO_REQUEST,
  UPDATE_IGISOKOZO_SUCCESS,
  UPDATE_IGISOKOZO_ERROR,
};
